### ISSUE TITLE
Allow reading results longer than screen height

### ISSUE THREAD

**Issue by intoinside** [c128lib/128spec#1]
Provide an option to consent unattended test suite running (as happens now, quite useful using Gradle) or stopping screen scrolling when used in manual mode (waiting for a key press before continue)

**Comment by johnpalermo** [comment]
Good idea!

**Comment by intoinside** [comment]
@johnpalermo i usually run spec test with Gradle, which generates a prg file that i can run inside Vice. Do you generate your prg in the same way? or you have another way to create and run it?
I found the correct point inside 128spec to set a breakpoint and wait for a key press but i need to understand when spec is running attended or unattended

**Comment by johnpalermo** [comment]
@intoinside In this case I just did a quick build and run with VSCode and KickAssembler by hitting F6 key. I didn't use gradle to build it.

**Comment by intoinside** [comment]
ok thank you, i'll test this evening. I've tried to reproduce build by hitting CTRL-SHIFT-B (don't know if it's like F6) and my fix worked, I hope it can work in all foreseen cases

**Comment by intoinside** [comment]
Done, every 5 test case it wait for a space bar press. Gradle works fine without interaction.
Version 0.7.4 available

**Comment by johnpalermo** [comment]
Thanks. Will try it on next test case.
